### ISSUE TITLE
`block in ffi_lib': Could not open library (...) libhttp-parser-ext.so

### ISSUE THREAD

**Issue by taraszka** [metanorma/ruby-packer#40]
I am trying to run my CLI application compiled using your rubyc implementation, and I am getting the error:

```
[info] Starting Script
/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux/libhttp-parser-ext.so': /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux/libhttp-parser-ext.so: cannot open shared object file: No such file or directory (LoadError)
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/ext.rb:8:in `<module:HttpParser>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/ext.rb:6:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser.rb:5:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser.rb:5:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/response/parser.rb:3:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/response/parser.rb:3:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/connection.rb:6:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/connection.rb:6:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/client.rb:9:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http/client.rb:9:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http.rb:8:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-4.4.1/lib/http.rb:8:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.10.1/lib/kubeclient/watch_stream.rb:2:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.10.1/lib/kubeclient/watch_stream.rb:2:in `<top (required)>'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.10.1/lib/kubeclient.rb:16:in `require'
	from /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.10.1/lib/kubeclient.rb:16:in `<top (required)>'
	from /__ruby_packer_memfs__/local/k8s-sanity-test.rb:12:in `require'
	from /__ruby_packer_memfs__/local/k8s-sanity-test.rb:12:in `<main>'
```

My simple program is using kubeclient gem and depends on http gem, which depends on http-parser.
Looking into the content of /tmp/rubyc/ I find this:

```
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/http-parser.gemspec
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/parser.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/types.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/version.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/errors.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/lib/http-parser/ext.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/LICENSE
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/Rakefile
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/README.md
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/spec
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/spec/parser_spec.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/spec/error_spec.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/spec/instance_spec.rb
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux/libhttp-parser-ext.so
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux/http-parser
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/x86_64-linux/http-parser/http_parser.o
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/Rakefile
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/http-parser
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/http-parser/http_parser.c
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-parser-1.2.3/ext/http-parser/http_parser.h
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/http-parser-1.2.3
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/http-parser-1.2.3/gem.build_complete
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/http-parser-1.2.3/gem_make.out
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/cache/http-parser-1.2.3.gem
./rubyc_work_dir/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/specifications/http-parser-1.2.3.gemspec
```

My program is trying to load all gems but fails:
```
$stderr.puts "[info] Starting Script"
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('./Gemfile', __dir__)
require 'bundler/setup'
require 'optparse'
require 'kubeclient'
require 'httparty'
require 'timeout'
require './parser'
require './static'
$stderr.puts "[info] Dependencies Loaded"
```

Any clue why it won't load it? What am I doing wrong?

**Comment by taraszka** [comment]
Gemfile:
```
source 'https://rubygems.org'

gem 'kubeclient', '4.10.1'
gem 'http-parser'
gem 'httparty'
```
